/*TMODJS:{"version":"1.0.0"}*/
!function(){
	function a(a,b){return(/string|function/.test(typeof b)?h:g)(a,b)}function b(a,c){return"string"!=typeof a&&(c=typeof a,"number"===c?a+="":a="function"===c?b(a.call(a)):""),a}function c(a){return l[a]}function d(a){return b(a).replace(/&(?![\w#]+;)|[<>"']/g,c)}function e(a,b){if(m(a))for(var c=0,d=a.length;d>c;c++)b.call(a,a[c],c,a);else for(c in a)b.call(a,a[c],c)}function f(a,b){var c=/(\/)[^/]+\1\.\.\1/,d=("./"+a).replace(/[^/]+$/,""),e=d+b;for(e=e.replace(/\/\.\//g,"/");e.match(c);)e=e.replace(c,"/");return e}function g(b,c){var d=a.get(b)||i({filename:b,name:"Render Error",message:"Template not found"});return c?d(c):d}function h(a,b){if("string"==typeof b){var c=b;b=function(){return new k(c)}}var d=j[a]=function(c){try{return new b(c,a)+""}catch(d){return i(d)()}};return d.prototype=b.prototype=n,d.toString=function(){return b+""},d}function i(a){var b="{Template Error}",c=a.stack||"";if(c)c=c.split("\n").slice(0,2).join("\n");else for(var d in a)c+="<"+d+">\n"+a[d]+"\n\n";return function(){return"object"==typeof console&&console.error(b+"\n\n"+c),b}}var j=a.cache={},k=this.String,l={"<":"&#60;",">":"&#62;",'"':"&#34;","'":"&#39;","&":"&#38;"},m=Array.isArray||function(a){return"[object Array]"==={}.toString.call(a)},n=a.utils={$helpers:{},$include:function(a,b,c){return a=f(c,a),g(a,b)},$string:b,$escape:d,$each:e},o=a.helpers=n.$helpers;a.get=function(a){return j[a.replace(/^\.\//,"")]},a.helper=function(a,b){o[a]=b},"function"==typeof define?define(function(){return a}):"undefined"!=typeof exports?module.exports=a:this.template=a,/*v:4*/
	a("banner",' <div class="banner-bar container"> <div class="banner"> <ul>  </ul> </div> <a href="#" class="unslider-arrow prev"></a><a href="#" class="unslider-arrow next"> </a> </div> '),/*v:2*/
	a("footer",' <div class="footer"> <div class=" container"> <div class="guild"> <ul> <li><a href="/ttw/page/ttw/portal/index.jsp">\u9996\u9875</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Design.jsp">\u5e73\u9762\u8bbe\u8ba1</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Virtual.jsp">\u865a\u62df\u4e3b\u673a</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Domain.jsp">\u57df\u540d\u6ce8\u518c</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Station.jsp">\u5efa\u7ad9\u8425\u9500</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Mailbox.jsp">\u4f01\u4e1a\u90ae\u7bb1</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Project.jsp">\u9879\u76ee\u6848\u4f8b</a></li> <li>|</li> <li><a href="/ttw/page/ttw/portal/html/Member.jsp">\u4f1a\u5458\u4e2d\u5fc3</a></li> <li>|</li> <li><a href="#">\u5e2e\u52a9\u4e2d\u5fc3</a></li> <li>|</li> <li><a href="#">\u5173\u4e8e\u6211\u4eec</a></li> <li>|</li> <li><a href="#">\u8054\u7cfb\u6211\u4eec</a></li> </ul> </div> <div class="copyright"> \u4eacICP\u590711017824\u53f7-4 / \u4eacICP\u8bc1130164\u53f7 \u5317\u4eac\u5e02\u516c\u5b89\u5c40\u671d\u9633\u5206\u5c40\u5907\u6848\u7f16\u53f7:110105000501</div> <div class="dateas"> Copyright \xa9 2006-2014 ZCOOL \u5168\u666f\u7edf\u8ba1</div> </div> </div> '),/*v:3*/
	//a("header",function(a){"use strict";var b=this,c=(b.$helpers,b.$each),d=a.list,e=(a.value,a.i,b.$string),f=a.Hlink,g="";return g+='<div class="header container"> <div class="h-nav"> <div class="container wid1000"> <ul class="fl leftsidebar"> <li><a href="/ttw/page/ttw/portal/index.jsp">\u9996\u9875</a></li> <li><a href="/ttw/page/ttw/portal/html/Design.jsp">\u5e73\u9762\u8bbe\u8ba1</a></li> <li><a href="/ttw/page/ttw/portal/html/Station.jsp">\u5efa\u7ad9\u8425\u9500</a></li> <li><a href="/ttw/page/ttw/portal/html/Virtual.jsp">\u865a\u62df\u4e3b\u673a</a></li> <li><a href="/ttw/page/ttw/portal/html/Domain.jsp">\u57df\u540d\u6ce8\u518c</a></li> <li><a href="/ttw/page/ttw/portal/html/Mailbox.jsp">\u4f01\u4e1a\u90ae\u7bb1</a></li> <li><a href="/ttw/page/ttw/portal/html/Project.jsp">\u9879\u76ee\u6848\u4f8b</a></li> </ul> <ul class="fr rightsidebar"> <li>[<a href="/ttw/page/ttw/portal/html/Et.jsp"> \u767b\u5f55</a> |<a href="/ttw/page/ttw/portal/html/Ef.jsp"> \u514d\u8d39\u6ce8\u518c</a> ] </li> <li><a href="/ttw/page/ttw/portal/html/NewPro/Submit.jsp">\u6211\u7684\u8ba2\u5355</a></li> </ul> </div> </div> <div class="h-sl"> <div class="container wid1000"> <a href="/ttw/page/ttw/portal/index.jsp"> <div class="logo fl"> </div> </a> <div class="search fr"> <div class="search-k fl"> <input class="search-input" placeholder="\u5c0a\u8d35\u578b\u8bbe\u8ba1" /> </div> <div class="search-xl fl"> <div class="dropdownContainer fl"> <div class="dropdownDefault">\u5206\u7c7b</div> <span class="downArrow1 arrow sx-icon"></span> <ul class="dropdrown-menu" style="display: none;"> <li>\u5206\u7c7b</li> <li>2</li> <li>6</li> <li>8</li> </ul> </div> </div> <div class="search-word fl"> \u641c \u7d22 </div> </div> </div> </div> <div class="h-menu"> <div class="container wid1000"> <ul class="leftsidebar2"> ',c(d,function(a,b){g+=" ",0===b?(g+=" <a href = ",g+=e(f[b]+"?t="+a),g+="><li><i></i>",g+=e(a),g+="</li></a> "):(g+=" <a href = ",g+=e(f[b]+"?t="+a),g+="><li>",g+=e(a),g+="</li></a> "),g+=" "}),g+=" </ul> </div> </div> </div> ",new k(g)})}();
	a("header",function(a){
		"use strict";var b=this,c=(b.$helpers,b.$each),d=a.list,e=(a.value,a.i,b.$string),f=a.Hlink,g="";
		
		var selectLi = a.selectLi;
		
		return g+= '',
			c(d,function(a,b){
				var selectStyle = "";
				if(selectLi == e(a)){
					selectStyle = "style='background:#fff; color:#0096dc'";
				}
				g+=" ",
				0===b?
						(g+=" <a href = ",g+=e(f[b]),g+="><li "+selectStyle+"><i></i>",g+=e(a),g+="</li></a> ")
					:
						(g+=" <a href = ",g+=e(f[b]),g+="><li "+selectStyle+">",g+=e(a),g+="</li></a> "),g+=" "}),
				g+=" </ul> </div> </div> </div> ",new k(g)
		
	})
}();